# Generated by Django 3.2.9 on 2022-01-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0002_auto_20220103_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Deleted', 'Deleted'), ('Pending', 'Pending')], default='Pending', max_length=12),
        ),
    ]
