# Generated by Django 3.2.9 on 2022-01-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0005_alter_shop_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Deleted', 'Deleted')], default='Pending', max_length=12),
        ),
    ]
