# Generated by Django 3.2.9 on 2022-01-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0006_auto_20220119_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('Deleted', 'Deleted'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending')], default='Pending', max_length=12),
        ),
    ]
