# Generated by Django 3.2.9 on 2022-01-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0009_alter_shop_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Deleted', 'Deleted'), ('Confirmed', 'Confirmed')], default='Pending', max_length=12),
        ),
    ]
