# Generated by Django 3.2.9 on 2021-12-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('pai', 'Paid'), ('unp', 'unpaid')], default='unp', max_length=3),
        ),
    ]
