# Generated by Django 3.2.9 on 2021-12-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('deleted', 'Deleted'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('pending', 'Pending')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
