# Generated by Django 3.2.9 on 2022-01-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('superuser', models.BooleanField(default=False, verbose_name='Is Super User')),
                ('seller', models.BooleanField(default=False, verbose_name='Is Seller')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
