# Generated by Django 3.2.9 on 2022-01-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
