# Generated by Django 3.2.9 on 2022-01-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otprequest',
            old_name='created_at',
            new_name='created',
        ),
    ]
