# Generated by Django 3.2.9 on 2022-01-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_created_at_otprequest_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
