# Generated by Django 3.2.9 on 2021-12-27 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Deleted', 'Deleted'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('shop_type', models.CharField(choices=[('bookshop', 'bookshop'), ('sweetshop', 'sweetshop'), ('dairy', 'dairy'), ('drugstore', 'drugstore')], max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_managing.shop')),
                ('tag', models.ManyToManyField(blank=True, null=True, to='shop_managing.Tag')),
            ],
        ),
    ]
