# Generated by Django 3.2.9 on 2021-12-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptype',
            name='status',
            field=models.CharField(choices=[('dai', 'dairy'), ('boo', 'bookshop'), ('swe', 'sweetshop'), ('dru', 'drugstore')], max_length=3),
        ),
    ]
