# Generated by Django 3.2.9 on 2021-12-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Deleted', 'Deleted'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10),
        ),
    ]
