# Generated by Django 3.2.9 on 2021-12-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('drugstore', 'drugstore'), ('bookshop', 'bookshop'), ('dairy', 'dairy'), ('sweetshop', 'sweetshop')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Deleted', 'Deleted')], default='Pending', max_length=10),
        ),
    ]
