# Generated by Django 3.2.9 on 2021-12-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0002_alter_shoptype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('con', 'Confirmed'), ('del', 'Deleted'), ('pen', 'Pending')], default='pen', max_length=3),
        ),
        migrations.AlterField(
            model_name='shoptype',
            name='status',
            field=models.CharField(choices=[('boo', 'bookshop'), ('dru', 'drugstore'), ('dai', 'dairy'), ('swe', 'sweetshop')], max_length=3),
        ),
    ]
