# Generated by Django 3.2.9 on 2021-12-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0002_auto_20211227_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('drugstore', 'drugstore'), ('dairy', 'dairy'), ('sweetshop', 'sweetshop'), ('bookshop', 'bookshop')], max_length=10),
        ),
    ]
