# Generated by Django 3.2.9 on 2021-12-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0003_alter_shop_shop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('drugstore', 'drugstore'), ('dairy', 'dairy'), ('bookshop', 'bookshop'), ('sweetshop', 'sweetshop')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('Deleted', 'Deleted'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10),
        ),
    ]
