# Generated by Django 3.2.9 on 2021-12-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0004_auto_20211226_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptype',
            name='status',
            field=models.CharField(choices=[('swe', 'sweetshop'), ('dai', 'dairy'), ('dru', 'drugstore'), ('boo', 'bookshop')], max_length=3),
        ),
    ]
