# Generated by Django 3.2.9 on 2021-12-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0004_auto_20211229_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('Deleted', 'Deleted'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=12),
        ),
    ]
