# Generated by Django 3.2.9 on 2021-12-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0004_auto_20211228_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('dairy', 'dairy'), ('drugstore', 'drugstore'), ('bookshop', 'bookshop'), ('sweetshop', 'sweetshop')], max_length=10),
        ),
    ]
