# Generated by Django 3.2.9 on 2021-12-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0005_alter_shop_shop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('bookshop', 'bookshop'), ('sweetshop', 'sweetshop'), ('drugstore', 'drugstore'), ('dairy', 'dairy')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Deleted', 'Deleted')], default='Pending', max_length=10),
        ),
    ]
