# Generated by Django 3.2.9 on 2022-01-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Canceled', 'Canceled'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending')], default='Pending', max_length=12),
        ),
    ]
