# Generated by Django 3.2.9 on 2022-01-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0003_alter_shop_status'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_managing.shop'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('deleted', 'Deleted'), ('confirmed', 'Confirmed')], default='pending', max_length=12),
        ),
    ]
