# Generated by Django 3.2.9 on 2022-01-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Paid', 'Paid'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=12),
        ),
    ]
