# Generated by Django 3.2.9 on 2022-01-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('paid', 'Paid'), ('pending', 'Pending'), ('deleted', 'Deleted')], default='pending', max_length=12),
        ),
    ]
