# Generated by Django 3.2.9 on 2022-01-20 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0006_auto_20220119_1411'),
        ('shopping', '0005_auto_20220117_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='shop_managing.shop'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Paid', 'Paid'), ('Canceled', 'Canceled')], default='Pending', max_length=12),
        ),
    ]
