# Generated by Django 3.2.9 on 2022-01-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Canceled', 'Canceled'), ('Paid', 'Paid'), ('Confirmed', 'Confirmed')], default='Pending', max_length=12),
        ),
    ]
