# Generated by Django 3.2.9 on 2022-01-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_alter_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Deleted', 'Deleted'), ('Paid', 'Paid'), ('Confirmed', 'Confirmed')], default='pending', max_length=12),
        ),
    ]
