# Generated by Django 3.2.9 on 2022-01-06 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_managing', '0005_alter_shop_status'),
        ('shopping', '0009_auto_20220106_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Deleted', 'Deleted'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Confirmed', 'Confirmed')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_managing.product'),
        ),
    ]
