# Generated by Django 3.2.9 on 2022-01-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20220106_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Paid', 'Paid'), ('Pending', 'Pending'), ('Deleted', 'Deleted')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='cart',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
