# Generated by Django 3.2.9 on 2022-01-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20220106_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Deleted', 'Deleted'), ('Paid', 'Paid'), ('Pending', 'Pending')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
