# Generated by Django 3.2.9 on 2022-01-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_auto_20220107_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Paid', 'Paid'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='pending', max_length=12),
        ),
    ]
